spring:
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: secret
    platform: postgres
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8091/auth/realms/automotive-ecom
          jwk-set-uri: http://localhost:8091/auth/realms/automotive-ecom/protocol/openid-connect/certs
  mail:
    host: smtp-mail.outlook.com
    username: javademo131@outlook.com
    password: Javax123
    port: 587
    properties:
      protocol: smtp
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  outlook:
    sender: javademo131@outlook.com


# SWAGGER
springdoc:
  api-docs:
    path: /api-docs
